---
version: '3'

services:
  backend:
    image: node:latest
    volumes:
      - "./app:/app"
    ports:
      - "8080:8080"
    working_dir: /app
    command: npm run dev
  mongo:
    image: mongo:latest
    env_file: ".dev.env"