on: 
  push:
    branches: [ "main" ]
  pull_request: 
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    name: Test and Build docker containers
    environment: Default
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set variable date
        run: date +%s
        id: get_date
      
      - name: Check if docker container exists
        id: get_docker_info
        run: sh -c "docker ps | awk -F '\n' '{print $3}'"

      - name: Stop old container
        run: sh -c 'docker stop aid_alert-backend'
        if: ${{ steps.get_docker_info.outputs.stdout }} != ""

      - name: Start new containers
        run: | 
          sh -c 'docker run 
          -e PORT=$PORT 
          -e ENVIRONMENT=$ENVIRONMENT 
          -e LOG_MODE=$LOG_MODE
          -e LOG_FILE=$LOG_FILE
          -e DATABASE_URL=$DATABASE_URL
          -e DATABASE_URI_TYPE=$DATABASE_URI_TYPE
          -e DATABASE_USER=$DATABASE_USER
          -e DAATABASE_PASSWORD=$DATABASE_PASSWORD
          -e DATABASE_NAME=$DATABASE_NAME
          --name=aid_alert-backend
          aid-alert_backend:$CONTAINER_VERSION'
        env:
          PORT: ${{ secrets.PORT || vars.PORT }} 
          ENVIRONMENT: ${{ secrets.ENVIRONMENT || vars.ENVIRONMENT }} 
          LOG_MODE: ${{ secrets.LOG_MODE || vars.LOG_MODE }}
          LOG_FILE: ${{ secrets.LOG_FILE || vars.LOG_FILE }}
          DATABASE_URL: ${{ secrets.DATABASE_URL || vars.DATABASE_URL }}
          DATABASE_URI_TYPE: ${{ secrets.DATABASE_URI_TYPE || vars.DATABASE_URI_TYPE }}
          DATABASE_USER: ${{ secrets.DATABASE_USER || vars.DATABASE_USER }}
          DAATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD || vars.DATABASE_PASSWORD }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME || vars.DATABASE_NAME }}
          DATABASE_ROOT_PASSWRD: ${{ secrets.DATABASE_ROOT_PASSWORD || vars.DATABASE_ROOT_PASSWORD }}
          CONTAINER_VERSION: ${{ steps.get_date.outputs.stdout }}