on: 
  push:
    branches: [ "main" ]
  pull_request: 
    branches: [ "main" ]

env:
  container_name: aid-alert_backend

jobs:
  setup:
    runs-on: self-hosted
    name: Setup Docker container ground
    environment: Default
    outputs:
      date: ${{ steps.get_date.outputs.date }}
      num_cont: ${{ steps.get_docker_info.outputs.num_cont }}
      container_existence: ${{ steps.get_container_info.outputs.}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set variable date
        run: echo "date=$(date +%s)" >> $GITHUB_OUTPUT
        id: get_date
      
      - name: Check if docker container exists
        id: get_docker_info
        run: echo "num_cont=$(docker ps | wc -l)" >> $GITHUB_OUTPUT
      
      - name: Check if container exists
        id: get_container_info
        run: echo "existence=$(docker ps -a -q -f name=$container_name)" >> $GITHUB_OUTPUT

  clean-and-build:
    runs-on: self-hosted
    name: Clean old container and build the new one.
    needs: setup
    if: ${{ needs.setup.outputs.container_existence == "" }}
    steps:
      - name: Stop  old container
        run: docker stop aid_alert-backend
      
      - name: Remove old container
        run: docker rm aid_alert-backend
        #if: needs.setup.outputs.num_cont > 1
      
      - name: Docker build
        run: docker build . --tag=$container_name:${{ needs.setup.outputs.date }}
  
  deploy:
    runs-on: self-hosted
    name: Deploy the new container.
    needs:
      - setup
      - clean-and-build
    steps:
      - name: Start new containers
        run: | 
          sh -c 'docker run \
          -e PORT=$PORT \
          -e ENVIRONMENT=$ENVIRONMENT \
          -e LOG_MODE=$LOG_MODE \
          -e LOG_FILE=$LOG_FILE \
          -e DATABASE_URL=$DATABASE_URL \
          -e DATABASE_URI_TYPE=$DATABASE_URI_TYPE \
          -e DATABASE_USER=$DATABASE_USER \
          -e DAATABASE_PASSWORD=$DATABASE_PASSWORD \
          -e DATABASE_NAME=$DATABASE_NAME \
          --name=aid_alert-backend \
          $container_name:$CONTAINER_VERSION'
        env:
          PORT: ${{ secrets.PORT || vars.PORT }} 
          ENVIRONMENT: ${{ secrets.ENVIRONMENT || vars.ENVIRONMENT }} 
          LOG_MODE: ${{ secrets.LOG_MODE || vars.LOG_MODE }}
          LOG_FILE: ${{ secrets.LOG_FILE || vars.LOG_FILE }}
          DATABASE_URL: ${{ secrets.DATABASE_URL || vars.DATABASE_URL }}
          DATABASE_URI_TYPE: ${{ secrets.DATABASE_URI_TYPE || vars.DATABASE_URI_TYPE }}
          DATABASE_USER: ${{ secrets.DATABASE_USER || vars.DATABASE_USER }}
          DAATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD || vars.DATABASE_PASSWORD }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME || vars.DATABASE_NAME }}
          DATABASE_ROOT_PASSWRD: ${{ secrets.DATABASE_ROOT_PASSWORD || vars.DATABASE_ROOT_PASSWORD }}
          CONTAINER_VERSION: ${{ needs.setup.outputs.date }}